= JDG Security Demo Application

This application shows how we can use security with https://developers.redhat.com/products/datagrid/overview/[JDG] via Access Control List (ACL)
or Role Based Access Control (RBAC).  This demo is a inspiration from https://github.com/tristantarrant[Tristan Tarrant]
 http://blog.infinispan.org/2014/07/infinispan-security-3-hotrod.html[blog] with adaptions done for the https://developers.redhat.com/products/datagrid/overview/[JDG 7.x]

This demo application will show to modules

* security using `<identiy-role-mapper/>` that is via JBoss EAP `application-users.properties`
 and `application-roles.properties`

* security using LDAP


== Adding security realm for ldap

This step is needed only if you are going to use LDAP for security. Assuming your JDG 7.x server us runing
and connectable via cli 9990



== Configuring JDG for Security

The following sections details the configuration changes that is required to be done in `clustered.xml`
to enable security for JDG caches/cache-containers



= References

* https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Data_Grid/7.0/html/Developer_Guide/part-Securing_Data_in_Red_Hat_JBoss_Data_Grid.html[Developer Guide]